### ISSUE TITLE
Error parse / create my self config file location !

### ISSUE THREAD

**Issue by MajurooTv** [SaherBlueEagle/BlueEagle-Endless-RAT#2]
Help me for this "error parse / create my self config file location, please check permissions for that/nerror  : Critical Update !!! How do you that ?? Tutorialpls

**Comment by SaherBlueEagle** [comment]
Kindly this issue will be closed as the tool is now pending , for a reason as mentioned within the README file , any issue regarding this tool , related to it`s not working will be removed
